### ISSUE TITLE
Reporting a post creates HTTP500 status and breaks admin overview of reported posts

### ISSUE THREAD

**Issue by nicopunto** [humhub-contrib/reportcontent#31]
❤️ ***THANK YOU VERY MUCH for creating this plugin!*** ❤️
***This is such a nice functionality add-on!***

**PROBLEM 1**
When reporting a post the overlay shows up fine, eveything seems to work but **when I hit send the loading spinner never goes away.** The page inspector shows that the request yields a 500 error/response. 
See: https://paste.pics/fa359850de452ba4090b8eca77e38a87

**PROBLEM 2**
After having tried to (unsuccessfully) report the first post, the admin view of reported content stops working: Before reporting, when I visit the "Reported content" menu item, I get a screen saying "nothing has been reported yet". After the failed report I get a general humhub message that I might have clicked a wrong link and there is a configuration error (not sure what the page reads in english… sorry)
See: https://paste.pics/6068768dbb407072c0d6e5186091ebb7

**VERSION INFO**
humhub: 1.4.0-beta.2 (currently latest beta)
reportcontent: downloaded the latest version from git. 0.2.5

**IN CASE THIS HELPS**
Here is a copy of the humhub protocol.
`yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\content\models\Content::user in /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/vendor/yiisoft/yii2/base/Component.php:154 Stack trace: #0 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('user') #1 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/modules/reportcontent/views/reportContentAdminGrid.php(31): yii\db\BaseActiveRecord->__get('user') #2 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/www/htdocs/w01...') #3 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/www/htdocs/w01...', Array) #4 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/www/htdocs/w01...', Array, NULL) #5 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/modules/reportcontent/views/admin/index.php(11): yii\base\View->render('/reportContentA...', Array) #6 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/www/htdocs/w01...') #7 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/www/htdocs/w01...', Array) #8 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/www/htdocs/w01...', Array, Object(humhub\modules\reportcontent\controllers\AdminController)) #9 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(386): yii\base\View->render('index', Array, Object(humhub\modules\reportcontent\controllers\AdminController)) #10 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/modules/reportcontent/controllers/AdminController.php(22): yii\base\Controller->render('index', Array) #11 [internal function]: humhub\modules\reportcontent\controllers\AdminController->actionIndex() #12 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #13 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #14 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #15 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('reportcontent/a...', Array) #16 /www/htdocs/w0135967/websites/siegerbettchen/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #17 /www/htdocs/w0135967/websites/siegerbettchen/humhub/index.php(25): yii\base\Application->run() #18 {main}
`

**Comment by buddh4** [comment]
Sorry for the late reply, there is a new version in the marketplace which fixes this issue.
