### ISSUE TITLE
Links in Notifications aren't trimmed

### ISSUE THREAD

**Issue by ArchBlood** [humhub-contrib/reportcontent#33]
When reporting a post with a link at the beginning (e.g embedded post) the link is shown and break the display

**Comment by buddh4** [comment]
Sorry for the late reply, can you maybe show me a screenshot?

**Comment by ArchBlood** [comment]
Once I'm back at the office I'll be sure to post one here

**Comment by ArchBlood** [comment]
Here you go :smile: 
![Screenshot_4](https://user-images.githubusercontent.com/35392110/101537613-c8507f00-3969-11eb-8145-406993b0ff61.png)

**Comment by buddh4** [comment]
Not sure what the problem is? Also how is this related to the reportcontent module?

**Comment by ArchBlood** [comment]
At the time of reporting this issue I only got the issue when a post that contained only a link was reported, just now noticed that liked or commented on notifications have the same outcome  :thinking:

**Comment by buddh4** [comment]
But what do you expect to see instead?

**Comment by ArchBlood** [comment]
Either links should be shortened to the extent that it doesn't line break or the text should be removed and a default "User1 has liked User2's post/comment" with no text :thinking:

**Comment by buddh4** [comment]
I'll close this for now since its not rleated with reportcontent and I'am not sure how or why a link like this should be shortened since this is just the text of the comment.
